# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Jay
  admin_email: jay.softwaredev@gmail.com
  admin_password: <%= ENV.fetch("WORK_ADMIN_DEV_PW") %> 
  email_provider_username: <%= ENV.fetch("GMAIL_USERNAME") %>
  email_provider_password: <%= ENV("GMAIL_PASSWORD") %>
  domain_name: workforeachother.herokuapp.com
  secret_key_base: fda74836e6103d44ea0797acb3b9048d0586f88da6fe3cef74e31a224dbaf9fddcc443e1b158bad6a6761b4066e91cfbca991b58f0b8c7d140ec166312e04ab0 

test:
  secret_key_base: fda74836e6103d44ea0797acb3b9048d0586f88da6fe3cef74e31a224dbaf9fddcc443e1b158bad6a6761b4066e91cfbca991b58f0b8c7d140ec166312e04ab0 

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
